// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PinjamRuanganAPI.Data;

#nullable disable

namespace PinjamRuanganAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260215174804_SeedPeminjamanData")]
    partial class SeedPeminjamanData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PinjamRuanganAPI.Entities.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlasanPeminjaman")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomorPeminjam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("WaktuMulai")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("WaktuSelesai")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("Peminjaman");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlasanPeminjaman = "Rapat UKM",
                            NamaPeminjam = "Budi",
                            NamaRuangan = "A101",
                            NomorPeminjam = "081234567890",
                            Status = "Menunggu",
                            Tanggal = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaktuMulai = new TimeSpan(0, 9, 0, 0, 0),
                            WaktuSelesai = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            AlasanPeminjaman = "Kelas tambahan",
                            NamaPeminjam = "Siti",
                            NamaRuangan = "B202",
                            NomorPeminjam = "089876543210",
                            Status = "Disetujui",
                            Tanggal = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaktuMulai = new TimeSpan(0, 13, 0, 0, 0),
                            WaktuSelesai = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            AlasanPeminjaman = "Seminar",
                            NamaPeminjam = "Andi",
                            NamaRuangan = "A101",
                            NomorPeminjam = "087700112233",
                            Status = "Ditolak",
                            Tanggal = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaktuMulai = new TimeSpan(0, 8, 0, 0, 0),
                            WaktuSelesai = new TimeSpan(0, 10, 0, 0, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
